import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { AsyncProvoder } from "./provider/query-provider";
import React from "react"

export const metadata: Metadata = {
  title: "Hono | nextjs",
  description: "Generated by hono",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col w-screen min-h-screen">
        <AsyncProvoder>

          <Header />
          {children} <Footer />
        </AsyncProvoder>
      </body>
    </html>
  );
}
